server:
  port: 9010
spring:
  application:
    name: gateway #服务名称
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/api/user/**
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/api/order/**
#          filters: #局部过滤器
#            - AddRequestHeader=Truth,faith is fucking awesome!
      default-filters: #默认过滤器
        - AddRequestHeader=Truth,faith is fucking awesome!